spring.application.name=store
spring.datasource.url=jdbc:postgresql://postgres:fHLgsxtRkDfULPMilavTsinfVhNCgCXc@postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=fHLgsxtRkDfULPMilavTsinfVhNCgCXc
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081